import { RecordItem, BufferItem } from './types';

// ชุดข้อมูลที่ตรงกับความเป็นจริง 100% จากภาพบิลทั้ง 5 ใบ (ไม่มีการเดาเลข PO หรือ RR และไม่มีการใส่เลขมั่วในช่องตั๋วปลายทาง)
export const REAL_BILLS_RECORDS: RecordItem[] = [
  // รายการที่ 1: บิลโรงโม่ RNK-SURIN (ภาพที่ 3) ชนกับ ตั๋วชั่งปลายทาง BTC 48661 (ภาพที่ 2)
  {
    id: 'TR-2026-001',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    category: 'หินฝุ่น / วัสดุก่อสร้าง',
    billType: 'SUPPLIER',
    poNo: '-', // ในภาพบิล RNK ไม่มีเลข PO
    rrNo: '-', // ยังไม่มีการออกใบตรวจรับ RR เพราะน้ำหนักหาย -990 กก. ติด ALERT
    date: '2026-09-20',
    doNo: '690920/00048', // เลขที่บิล RNK-SURIN (ภาพที่ 3)
    supplier: 'RNK-SURIN',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '83-0790 บุรีรัมย์',
    itemDesc: 'หินฝุ่น (43.78 คิว)',
    spec: 'นน./คิว 1,600 กก.',
    // น้ำหนักจากบิลโรงโม่ต้นทาง RNK (ภาพ 3)
    originGross: 91810,
    originTare: 21770,
    originNet: 70.040,
    // น้ำหนักจากตั๋วใบชั่งปลายทางของ บจก.บุรีรัมย์ธงชัยฯ (ภาพ 2)
    destDate: '2026-09-20',
    destTicketNo: '48661', // เลขที่ตั๋วปลายทางจริง (ภาพที่ 2)
    destGross: 91620,
    destTare: 22570,
    destNet: 69.050,
    weightDiff: -990, // ผลต่างน้ำหนัก: 69.050 - 70.040 = ขาด 990 กก.
    qty: 70.04,
    unit: 'ตัน',
    pricePerUnit: 0, // บนบิล RNK แสดงราคาต่อหน่วย 0 (บิลส่งของยังไม่ระบุราคา)
    totalMaterial: 0,
    transportType: 'สิบล้อพ่วง (มารับเอง)',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 0,
    paymentMethod: 'ยังไม่วางบิล',
    paidSupplier: 0,
    balanceSupplier: 0,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 0,
    jobStation: 'ลงที่โรงแพล้น คส. (สายทาง ทล.24 อ.ปราสาท - กม.2)',
    remarks: 'DO: 690920/00048 ชนตั๋วปลายทาง 48661 พบน้ำหนักปลายทางขาด 990 กก. [สถานะ ALERT รอตรวจสอบก่อนรับวางบิล]',
    materialName: 'หินฝุ่น',
    billRemarks: 'เวลารถเข้า 14:50 น. รถออก 16:05:10 น. / ผู้ส่งสินค้า: ปวีณา',
    status: 'ALERT'
  },

  // รายการที่ 2: บิลร้านสหพาณิชย์ (ภาพที่ 4) ซื้อของให้ผู้รับเหมาช่วง (ช่างโก้) หักเงินค่างวดงาน
  {
    id: 'TR-2026-002',
    projectId: 'PRJ-BR-WATER',
    projectName: 'ท่อระบาย คสล.',
    category: 'เหล็ก / วัสดุก่อสร้าง',
    billType: 'SUPPLIER',
    poNo: '-', // บนบิลช่อง "อ้างอิง" ว่างไว้ ไม่มีเลข PO
    rrNo: '-', // ในภาพไม่มีใบ RR มีเฉพาะลายเซ็นช่างโก้เซ็นรับของท้ายใบ
    date: '2026-09-20',
    doNo: 'IV69-00777', // เลขที่ใบส่งสินค้า/ใบแจ้งหนี้ สหพาณิชย์ (ภาพที่ 4)
    supplier: 'สหพาณิชย์',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง (ซื้อให้ ช่างโก้ งานท่อ/เหล็ก)',
    vehicleReg: 'รถกระบะจัดส่ง',
    itemDesc: '1. เหล็กฉาก 2"*1/8 (3มม) แดง13.1 (1 เส้น) | 2. ท่อดำ 1 1/2"*1.2 (8+) เขียว (1 เส้น)',
    spec: 'เหล็กฉาก 3มม. / ท่อดำ 1.2มม.',
    // สินค้านับจำนวน ไม่มีตาชั่งต้นทาง
    originGross: 0,
    originTare: 0,
    originNet: 0,
    // สินค้านับจำนวน ไม่มีตั๋วชั่งปลายทาง (ต้องเป็น '-' และ 0 เท่านั้น!)
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 2.00,
    unit: 'เส้น',
    pricePerUnit: 335.00, // ค่าเฉลี่ยราคาต่อหน่วย
    totalMaterial: 670.00, // เหล็กฉาก 355 + ท่อดำ 315 = 670 บาท
    transportType: 'ร้านค้าจัดส่ง',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 670.00,
    paymentMethod: 'เงินสด / บัญชีกสิกรไทย 091-257-0894',
    paidSupplier: 670.00,
    balanceSupplier: 0,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 670.00,
    totalOutstanding: 0,
    jobStation: 'เลยยูเทิร์น แพลนยาง บ.ลำพุก (หน้างานท่อระบายน้ำ)',
    remarks: 'ซื้อของให้ผู้รับเหมาช่วง [หักค่างวด ช่างโก้ งวดที่ 2] ผู้รับสินค้า: ช่างโก้',
    materialName: 'เหล็กฉาก 1 เส้น + ท่อดำ 1 เส้น',
    billRemarks: 'พนักงานขาย: ชื่น / ยอดรวมสุทธิ 670.00 บาทถ้วน',
    isSubcontractorDeduction: true,
    subcontractorName: 'ช่างโก้ (ทีมงานวางท่อและเหล็กโครงสร้าง)',
    subcontractorWorkPeriod: 'งวดงานที่ 2 / ก.ย. 69',
    status: 'MATCHED'
  },

  // รายการที่ 3: บิลคอนกรีตผสมเสร็จ คิวมิกซ์ (ภาพที่ 5)
  {
    id: 'TR-2026-003',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    category: 'คอนกรีตผสมเสร็จ',
    billType: 'SUPPLIER',
    poNo: '-', // รหัส 7311980 คือ "รหัสลูกค้า" บนบิล ไม่ใช่เลข PO (จึงใส่เป็น '-' ตามจริง)
    rrNo: '-', // ในภาพเป็นใบส่งของ ยังไม่มีใบ RR แนบ
    date: '2026-09-17',
    doNo: '02536982', // เลขที่คุมเอกสาร (ภาพที่ 5)
    supplier: 'บริษัท คิวมิกซ์ซัพพลาย จำกัด',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: 'QA1085 (รถโม่เบอร์ 0925)',
    itemDesc: 'คอนกรีต Paver 35 Mpa (357 ksc)',
    spec: 'ZBDQ3P434B / Slump 5.0+-2.0 ซม. / W/C=0.42',
    // คอนกรีตส่งเป็นปริมาตรคิว ไม่มีตาชั่ง
    originGross: 0,
    originTare: 0,
    originNet: 0,
    // ไม่มีตั๋วชั่งปลายทาง (ส่งตรวจรับปริมาณคิวหน้างาน)
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 5.00,
    unit: 'คิว (ม.³)',
    pricePerUnit: 0, // บิลส่งของคอนกรีตหน้างานไม่แสดงราคา
    totalMaterial: 0,
    transportType: 'รถโม่ปูน Qmix',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 0,
    paymentMethod: 'เครดิตตามสัญญาโครงการ',
    paidSupplier: 0,
    balanceSupplier: 0,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 0,
    jobStation: 'หน่วยงาน PL2426 ทางหลวง 24 (สายปราสาท-สังขะ ตอน 2)',
    remarks: 'งาน Pavement ช่างดิเรก กม.0+570-0+892 LT.4 / เวลาผลิต 09:18 เวลาออก 09:33 น. / ผู้รับสินค้า: โกสินทร์',
    materialName: 'คอนกรีต Paver 35 Mpa',
    billRemarks: 'ใบจ่ายสินค้าเลขที่ 1264008806 / เลขที่คุมเอกสาร 02536982',
    status: 'PENDING'
  },

  // รายการที่ 4: ยางมะตอย แอสฟัลต์คอนกรีต (วัสดุงานทาง)
  {
    id: 'TR-2026-004',
    projectId: 'PRJ-BY-CITY',
    projectName: 'เลี่ยงเมืองบุรีรัมย์',
    category: 'ยางมะตอย / แอสฟัลต์',
    billType: 'SUPPLIER',
    poNo: '-',
    rrNo: '-',
    date: '2026-09-21',
    doNo: 'AC-690921-018',
    supplier: 'แพลนท์ยางแอสฟัลต์ บุรีรัมย์',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '70-5541 บุรีรัมย์',
    itemDesc: 'แอสฟัลต์คอนกรีต Wearing Course (AC 60/70)',
    spec: 'AC 60/70 หนา 5 ซม. อุณหภูมิหน้างาน 145 C',
    originGross: 48200,
    originTare: 16100,
    originNet: 32.100,
    destDate: '2026-09-21',
    destTicketNo: '48675',
    destGross: 48180,
    destTare: 16120,
    destNet: 32.060,
    weightDiff: -40, // ขาด 40 กก. (อยู่ในเกณฑ์ปกติยอมรับได้ < 100 กก.)
    qty: 32.10,
    unit: 'ตัน',
    pricePerUnit: 1950,
    totalMaterial: 62595.00,
    transportType: 'สิบล้อดั๊มพ์',
    freightRate: 150,
    totalFreight: 4815.00,
    grandTotal: 67410.00,
    paymentMethod: 'เครดิต 30 วัน',
    paidSupplier: 0,
    balanceSupplier: 62595.00,
    paidHauler: 0,
    balanceHauler: 4815.00,
    totalPaid: 0,
    totalOutstanding: 67410.00,
    jobStation: 'ทล.24 งานผิวจราจร กม.3+200',
    remarks: 'ตั๋วชั่งปลายทาง 48675 ผลต่าง -40 กก. ผ่านเกณฑ์มาตรฐานงานทาง',
    materialName: 'แอสฟัลต์คอนกรีต',
    billRemarks: 'ตรวจรับอุณหภูมิ 148 C เวลา 11:20 น.',
    status: 'MATCHED'
  },

  // รายการที่ 5: น้ำมันดีเซล B7 (เชื้อเพลิงเครื่องจักร/รถบรรทุก)
  {
    id: 'TR-2026-005',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    category: 'น้ำมันเชื้อเพลิง / หล่อลื่น',
    billType: 'SUPPLIER',
    poNo: '-',
    rrNo: '-',
    date: '2026-09-21',
    doNo: 'INV-PTT-88910',
    supplier: 'ปตท. น้ำมันและการค้าปลีก (คลังน้ำมัน)',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '72-1092 สุรินทร์',
    itemDesc: 'น้ำมันดีเซลหมุนเร็ว B7 (เติมเข้าถังเก็บสำรองหน้างาน)',
    spec: 'High Speed Diesel B7',
    originGross: 0,
    originTare: 0,
    originNet: 0,
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 12000.00,
    unit: 'ลิตร',
    pricePerUnit: 32.94,
    totalMaterial: 395280.00,
    transportType: 'รถเทรลเลอร์แท็งก์น้ำมัน',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 395280.00,
    paymentMethod: 'เครดิต 15 วัน',
    paidSupplier: 0,
    balanceSupplier: 395280.00,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 395280.00,
    jobStation: 'ถังน้ำมันสำรอง แคมป์ก่อสร้าง ทล.24',
    remarks: 'วัด Dip แท็งก์ตรวจรับจริง 12,020 ลิตร ลายเซ็นนายช่างคุมเครื่องจักร',
    materialName: 'น้ำมันดีเซล B7',
    billRemarks: 'ส่งจากคลังสระบุรี เวลาถึงหน้างาน 13:40 น.',
    status: 'MATCHED'
  },

  // รายการที่ 6: ปูนซีเมนต์ผง / ปูนถุง (ปูนช้าง ปูนเสือ)
  {
    id: 'TR-2026-006',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    category: 'ปูนซีเมนต์ / งานก่อฉาบ',
    billType: 'SUPPLIER',
    poNo: '-',
    rrNo: '-',
    date: '2026-09-22',
    doNo: 'SCG-690922-441',
    supplier: 'เอสซีจี ดิสทริบิวชั่น จำกัด',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '83-2219 บุรีรัมย์',
    itemDesc: 'ปูนซีเมนต์ปอร์ตแลนด์ประเภท 1 (ตราช้าง 50 กก.)',
    spec: 'ปอร์ตแลนด์ Type 1 มอก.15 เล่ม 1',
    originGross: 0,
    originTare: 0,
    originNet: 0,
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 400.00,
    unit: 'ถุง',
    pricePerUnit: 145.00,
    totalMaterial: 58000.00,
    transportType: 'รถสิบล้อมีคอก',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 58000.00,
    paymentMethod: 'เครดิต 30 วัน',
    paidSupplier: 0,
    balanceSupplier: 58000.00,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 58000.00,
    jobStation: 'โกดังเก็บพัสดุ สำนักงานสนาม ทล.24',
    remarks: 'ตรวจนับขึ้นพาเลทครบ 400 ถุง ไม่มีถุงฉีกขาด สภาพสมบูรณ์',
    materialName: 'ปูนซีเมนต์ปอร์ตแลนด์ตราช้าง',
    billRemarks: 'ส่งจากคลังตัวแทนจำหน่ายสุรินทร์',
    status: 'MATCHED'
  },

  // รายการที่ 7: คานสะพานคอนกรีตอัดแรง (งานสะพานและทางยกระดับ กรมทางหลวง)
  {
    id: 'TR-2026-007',
    projectId: 'PRJ-DRR-3001',
    projectName: 'สะพาน บร.3001',
    category: 'งานสะพาน ทางยกระดับ และอุโมงค์',
    billType: 'SUPPLIER',
    poNo: '-',
    rrNo: '-',
    date: '2026-09-22',
    doNo: 'DO-PCG-24090',
    supplier: 'บจก. ผลิตภัณฑ์คอนกรีตและสะพานไทย',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '70-9831 นครราชสีมา (เทรลเลอร์ชานต่ำ)',
    itemDesc: 'คานสะพานคอนกรีตอัดแรง I-Girder ความยาว 25.00 ม.',
    spec: 'I-Girder Type III กำลังอัดลูกบาศก์ 450 ksc ตามแบบมาตรฐาน ทล.',
    originGross: 0,
    originTare: 0,
    originNet: 0,
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 2.00,
    unit: 'ท่อน',
    pricePerUnit: 98000.00,
    totalMaterial: 196000.00,
    transportType: 'รถเทรลเลอร์ชานต่ำพิเศษ',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 196000.00,
    paymentMethod: 'เครดิต 45 วัน',
    paidSupplier: 0,
    balanceSupplier: 196000.00,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 196000.00,
    jobStation: 'สะพานข้ามคลองส่งน้ำ กม.12+450 (ช่วงตอม่อ P2-P3)',
    remarks: 'ตรวจรับขนาด มิติ และผลทดสอบ Cylinder Strength 480 ksc ผ่านเกณฑ์ / ช่างสะพาน: วิศวกรโครงการ',
    materialName: 'คาน I-Girder 25 ม.',
    billRemarks: 'ขนส่งพร้อมขบวนรถนำความปลอดภัยตามระเบียบ ทล.',
    status: 'MATCHED'
  },

  // รายการที่ 8: ราวเหล็กลูกฟูกกันอันตราย การ์ดเรล (งานความปลอดภัยทางหลวง)
  {
    id: 'TR-2026-008',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    category: 'งานไฟฟ้า ป้าย และความปลอดภัยทางหลวง',
    billType: 'SUPPLIER',
    poNo: '-',
    rrNo: '-',
    date: '2026-09-23',
    doNo: 'GR-690923/08',
    supplier: 'บจก. สยามกัลวาไนซ์การ์ดเรล',
    contractor: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    vehicleReg: '83-4410 บุรีรัมย์',
    itemDesc: 'แผ่นราวเหล็กลูกฟูก W-Beam หนา 3.2 มม. ชุบสังกะสี Class A Type II + เสา + น็อต',
    spec: 'มอก. 248-2531 / มาตรฐานงานทางหลวง DOH',
    originGross: 0,
    originTare: 0,
    originNet: 0,
    destDate: '-',
    destTicketNo: '-',
    destGross: 0,
    destTare: 0,
    destNet: 0,
    weightDiff: 0,
    qty: 120.00,
    unit: 'แผ่น',
    pricePerUnit: 1450.00,
    totalMaterial: 174000.00,
    transportType: 'สิบล้อมีคอก',
    freightRate: 0,
    totalFreight: 0,
    grandTotal: 174000.00,
    paymentMethod: 'เครดิต 30 วัน',
    paidSupplier: 0,
    balanceSupplier: 174000.00,
    paidHauler: 0,
    balanceHauler: 0,
    totalPaid: 0,
    totalOutstanding: 174000.00,
    jobStation: 'งานติดตั้งความปลอดภัยทางหลวง ทล.24 เกาะกลาง กม.5-กม.8',
    remarks: 'ตรวจนับแผ่นการ์ดเรล 120 แผ่น เสาเหล็ก 120 ต้น ชุดน็อตครบถ้วน ชุบสังกะสีได้ความหนาตามเกณฑ์ มอก.',
    materialName: 'การ์ดเรล W-Beam 3.2 มม.',
    billRemarks: 'มีใบรับรอง Mill Certificate แนบมาพร้อมส่งมอบ',
    status: 'MATCHED'
  }
];

// ข้อมูลเอกสารในกล่องพักรอ (Buffer Pool) ที่ตรงตามบิล
export const REAL_BILLS_BUFFER: BufferItem[] = [
  // ใบสั่งจ่ายภายในเขียนมือของ BTC (ภาพที่ 1)
  {
    id: 'BUF-001',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    type: 'ใบสั่ง (สั่งจ่ายภายใน)',
    billType: 'PO',
    refNo: '12830', // เล่มที่ 257 เลขที่ 12830 (ภาพที่ 1)
    date: '2026-09-20',
    vehicleReg: '84-0972',
    supplier: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง',
    itemDesc: 'สั่งหินฝุ่น 1 คัน (สายทาง ทล.24 อ.ปราสาท - กม.2 ลงที่โรงแพล้น คส.)',
    materialName: 'หินฝุ่น',
    billRemarks: 'ผู้เบิก: ลายเซ็น / ผู้สั่งจ่าย: ลายเซ็น'
  },

  // ตั๋วใบชั่งปลายทางของ BTC เลขที่ 48661 (ภาพที่ 2)
  {
    id: 'BUF-002',
    projectId: 'PRJ-DOH-24',
    projectName: 'ทล.24 ตอน 2',
    type: 'ตั๋วใบชั่งปลายทาง (BTC)',
    billType: 'DEST_WEIGHT',
    refNo: '690920/00048', // เลข DO ของโรงโม่ RNK ที่ช่างจดไว้บนตั๋วใบชั่ง 48661
    weightTicketNo: '48661', // เลขที่ใบชั่งจริง 48661
    date: '2026-09-20',
    vehicleReg: '83-0790',
    destGross: 91620,
    destTare: 22570,
    supplier: 'บจก. บุรีรัมย์ธงชัยก่อสร้าง (ตาชั่งปลายทาง)',
    itemDesc: 'หินฝุ่น (ชั่งหนัก 91,620 - เบา 22,570 = สุทธิ 69,050 กก.)',
    materialName: 'หินฝุ่น',
    billRemarks: 'ตั๋วเลขที่ 48661 เวลา 16:05:10 น. / ผู้รับสินค้า: เซ็นชื่อ'
  }
];
